# Generated by Django 3.0.6 on 2020-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(default='background.jpg', upload_to='bg_pic/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='anni',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='descrizione',
            field=models.CharField(default='La tua fantastica descrizione', max_length=4000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='immagine',
            field=models.ImageField(default='default.png', upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sesso',
            field=models.TextField(choices=[('Maschio', 'Maschio'), ('Femmina', 'Femmina'), ('Nessuno', 'Nessuno')], default='Nessuno'),
        ),
    ]
