# Generated by Django 3.0.6 on 2020-05-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=250)),
                ('contenuto', models.TextField(blank=True)),
                ('creato', models.DateField(default='2020-05-15')),
                ('scade_il', models.DateField(default='2020-05-15')),
                ('orario', models.TimeField()),
                ('tag', models.TextField(blank=True)),
                ('pubblica', models.TextField(choices=[('Privata', 'Privata'), ('Pubblica', 'Pubblica')], default='Privata')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creato'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autore', models.CharField(max_length=80)),
                ('testo', models.TextField()),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo_platform.TodoList')),
            ],
            options={
                'ordering': ['creato'],
            },
        ),
    ]
