# Generated by Django 3.0.6 on 2020-05-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='creato',
            field=models.DateField(default='2020-05-19'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='scade_il',
            field=models.DateField(default='2020-05-19'),
        ),
    ]
